JustBlog.Web/Areas/Admin/Controllers/GalleryController.cs
using JustBlog.Services.GalleryImage;
using JustBlog.Services.Post;
using JustBlog.ViewModels.GalleryImage;
using JustBlog.ViewModels.Others;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace JustBlog.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class GalleryController : Controller
    {
        private readonly IGalleryImageService _galleryService;
        private readonly IPostService _postService;

        public GalleryController(IGalleryImageService galleryService, IPostService postService)
        {
            _galleryService = galleryService;
            _postService = postService;
        }

        [Authorize(policy: "Get")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(policy: "Get")]
        public IActionResult GetPagedGallery(int page, int pageSize)
        {
            var images = _galleryService.GetPagedImages(page, pageSize);
            var total = _galleryService.CountAllImages();
            var dataTable = new DataTableViewModel
            {
                Action = "GetPagedImages",
                Controller = "Gallery",
                Total = total,
                Page = page,
                LastPage = (int)Math.Ceiling((double)total / pageSize),
                PageSize = pageSize,
                Columns = new string[] { "Id", "Title", "Description", "ImageUrl", "Create Date", "Created By" },
                Data = images.Select(image =>
                    new Dictionary<string, string>
                    {
                        { "Id", image.Id.ToString() },
                        { "Title",image.Title.ToString() },
                        { "Description", image.Description },
                        { "ImageUrl", image.ImageUrl },
                        { "Created Date", image.CreatedDate.ToString() },
                        { "Created By", image.CreatedBy.ToString() }
                    }
                ).ToList()
            };
            return PartialView("_DataTablePartial", dataTable);
        }

        [Authorize(policy: "Get")]
        public IActionResult Details(int id)
        {
            var ImageDetails = _galleryService.GetImageDetails(id);
            return View(ImageDetails);
        }

        [Authorize(policy: "Create Or Edit")]
        public IActionResult Create()
        {
            ViewBag.Posts = _postService.GetAllPosts();
            return View();
        }

        [Authorize(policy: "Create Or Edit")]
        [HttpPost]
        public IActionResult Create(GalleryToCreateViewModel ImageToCreate)
        {
            if (ModelState.IsValid && _galleryService.AddImage(ImageToCreate))
                return Redirect("/Admin/Image");
            ViewBag.Posts = _postService.GetAllPosts();
            return View(ImageToCreate);

        }

        [Authorize(policy: "Create Or Edit")]
        public IActionResult Edit(int id)
        {
            var editImage = _galleryService.GetImageToUpdate(id);
            if (editImage == null)
                return View("NotFound");

            ViewBag.Posts = _postService.GetAllPosts();
            return View(editImage);
        }

        [Authorize(policy: "Create Or Edit")]
        [HttpPost]
        public IActionResult Edit(GalleryToUpdateViewModel ImageToUpdate)
        {
            if (ModelState.IsValid)
            {
                if (_galleryService.UpdateImage(ImageToUpdate))
                    ViewBag.Message = "Update Image successfully";
                else
                    ViewBag.Message = "Update Image failed";
            }

            ViewBag.Posts = _postService.GetAllPosts();
            return View(ImageToUpdate);
        }

        [Authorize(policy: "Delete")]
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            if (_galleryService.DeleteImage(id))
                return StatusCode(200);
            return View("NotFound");
        }
    }
}

JustBlog.Web/Controllers/GalleryController.cs
using JustBlog.Services.GalleryImage;
using Microsoft.AspNetCore.Mvc;

namespace JustBlog.Web.Controllers
{
    public class GalleryController : Controller
    {
        private readonly IGalleryImageService _galleryImageService;

        public GalleryController(IGalleryImageService galleryImageService)
        {
            _galleryImageService = galleryImageService;
        }

        public IActionResult Index()
        {
            var images = _galleryImageService.GetAllImages();
            return View(images.ToList());
        }
    }
}

JustBlog.Web/Controllers/PostController.cs
using JustBlog.Services.Post;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace JustBlog.Web.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _postService;

        public PostController(IPostService postService)
        {
            _postService = postService;
        }

        // GET: PostController
        public IActionResult Index()
        {
            var posts = _postService.GetAllPostsWithCategoryAndTags();
            return View(posts);
        }

        public IActionResult AboutCard()
        {
            return PartialView("Component/_AboutCardPartial");
        }

        [ActionName("Latest")]
        public IActionResult LatestPost()
        {
            int size = 5;
            var posts = _postService.GetLatestPosts(size);
            return View(posts);
        }

        public IActionResult LatestPosts()
        {
            int size = 5;
            var posts = _postService.GetLatestPosts(size);
            return PartialView("Component/_ListPostsPartial", posts);
        }
        public IActionResult MostViewedPosts()
        {
            int size = 5;
            var posts = _postService.GetMostViewedPosts(size);
            return PartialView("Component/_ListPostsPartial", posts);
        }

        [Route("post/{year}/{month}/{slug}")]
        public IActionResult Details(int year, int month, string slug)
        {
            var post = _postService.GetDetailOfPosts(year, month, slug);
            if (post == null)
                return View("NotFound");
            return View(post);
        }
    }
}

JustBlog.Web/Views/Gallery/Index.cshtml
@{
    ViewData["Title"] = "Gallery";
}

@model List<GalleryViewModel>

<!-- Page Header-->
<header class="masthead" style="background-image: url('/assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Life Ideas</h1>
                    <span class="subheading">Ignite your thoughts, Illuminate the world</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="justify-content-center">
    <div class="row" id="imageGallery">

        @if (Model != null && Model.Count() > 0)
        {
            @foreach (var item in Model)
            {
                @*var post = @posts.FirstOrDefault(p => p.Id == @item.PostId);*@
                @*<a asp-action="Detail" asp-controller="Post" asp-route-year="@post.PostedOn.Year" asp-route-month="@post.PostedOn.Month" asp-route-title="@post.Title">*@
                <div class="col-md-4">
                    <div class="galleryhome">
                        <img class="myImg" src="@Url.Content(item.ImageUrl)" alt="@item.Title" width="600" height="400">
                        <div class="desc">@item.Description</div>

                        <!-- The Modal -->
                        <div id="myModal" class="modal">
                            <img class="modal-content" id="img01">
                            <div id="caption"></div>
                        </div>
                    </div>
                </div>
                @*</a>*@
            }
        }
    </div>

    <!-- Pager -->
    <div id="pagination" class="d-flex justify-content-center">
        <a class="btn btn-primary text-uppercase" id="pageImagesLink">Next page →</a>
    </div>
</div>
<script>
    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the images and insert them inside the modal - use their "alt" text as captions
    var images = document.getElementsByClassName("myImg");
    var modalImg = document.getElementById("img01");
    var captionText = document.getElementById("caption");

    for (var i = 0; i < images.length; i++) {
        images[i].onclick = function () {
            modal.style.display = "block";
            modalImg.src = this.src;
            captionText.innerHTML = this.alt;
        }
    }

    // Close the modal when clicking anywhere on the screen
    window.onclick = function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>